### ISSUE TITLE
Cope with zero-length WARCs

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#100]
We very rarely have zero-length WARCs on the system (due to e.g. transient errors in sparse crawls). The current system fails whole jobs when it hits them, but it should really grumble and move on.

```
WARN  NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
INFO  ArchiveFileRecordReader - Processing path: hdfs://nellie:54310/heritrix/output/warcs/monthly-051500/20140706000220/BL-20140706002644688-00000-17066~opera~8446.warc.gz
Processing path: hdfs://nellie:54310/heritrix/output/warcs/monthly-051500/20140706000220/BL-20140706002644688-00000-17066~opera~8446.warc.gz
INFO  ArchiveFileRecordReader - Opening nextFile: hdfs://nellie:54310/heritrix/output/warcs/monthly-051500/20140706000220/BL-20140706002644688-00000-17066~opera~8446.warc.gz
WARN  Child - Error running child
java.io.EOFException
	at org.archive.util.zip.OpenJDK7GZIPInputStream.readUByte(OpenJDK7GZIPInputStream.java:270)
	at org.archive.util.zip.OpenJDK7GZIPInputStream.readUShort(OpenJDK7GZIPInputStream.java:260)
	at org.archive.util.zip.OpenJDK7GZIPInputStream.readHeader(OpenJDK7GZIPInputStream.java:169)
	at org.archive.util.zip.OpenJDK7GZIPInputStream.<init>(OpenJDK7GZIPInputStream.java:84)
	at org.archive.util.zip.GZIPMembersInputStream.<init>(GZIPMembersInputStream.java:79)
	at org.archive.util.zip.GZIPMembersInputStream.<init>(GZIPMembersInputStream.java:74)
	at org.archive.io.warc.WARCReaderFactory$CompressedWARCReader.<init>(WARCReaderFactory.java:252)
	at org.archive.io.warc.WARCReaderFactory.getArchiveReader(WARCReaderFactory.java:113)
	at org.archive.io.warc.WARCReaderFactory.get(WARCReaderFactory.java:99)
	at org.archive.io.ArchiveReaderFactory.getArchiveReader(ArchiveReaderFactory.java:155)
	at org.archive.io.ArchiveReaderFactory.get(ArchiveReaderFactory.java:144)
	at uk.bl.wa.hadoop.ArchiveFileRecordReader.nextFile(ArchiveFileRecordReader.java:140)
	at uk.bl.wa.hadoop.ArchiveFileRecordReader.<init>(ArchiveFileRecordReader.java:59)
	at uk.bl.wa.hadoop.ArchiveFileInputFormat.getRecordReader(ArchiveFileInputFormat.java:19)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:371)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:325)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
	at org.apache.hadoop.mapred.Child.main(Child.java:264)
```

**Comment by anjackson** [comment]
@GilHoggarth latest commit (c65a078) should fix this, I think.

**Comment by anjackson** [comment]
@GilHoggarth - apparently this didn't work?

**Comment by GilHoggarth** [comment]
http://194.66.232.87:50030/jobdetails.jsp?jobid=job_201707181600_0332&refresh=30 failed last time, which is using the new code.

**Comment by GilHoggarth** [comment]
Which has failed again.

**Comment by anjackson** [comment]
Once more, with feeling.

**Comment by anjackson** [comment]
Okay, working now.
