### ISSUE TITLE
FontBox multiple versions on classpath?

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#104]
We're seeing a report of:

```
Exception in thread "1501828702345" java.lang.NoSuchMethodError: org.apache.fontbox.ttf.TTFParser.parse(Ljava/io/InputStream;)Lorg/apache/fontbox/ttf/TrueTypeFont;
    at org.apache.tika.parser.font.TrueTypeParser.parse(TrueTypeParser.java:70)
    at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
    at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
    at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:135)
    at uk.bl.wa.solr.TikaExtractor$ParseRunner.run(TikaExtractor.java:429)
    at java.lang.Thread.run(Thread.java:748)
```

Since upgrading Tika, we may have multiple versions of these libs on the classpath. It's possible we're not seeing them in production because additional PDF manipulation stuff is disabled.

**Comment by anjackson** [comment]
@thomasegense I think this should resolve the version clash you observed.

**Comment by thomasegense** [comment]
Can confirm indexing is working. However the warc-indexer is spamming the log with the following exceptions:
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSerif' for 'TimesNewRomanPSMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-Bold' for 'Arial-BoldMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-BoldItalic' for 'Arial-BoldItalicMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-Italic' for 'Arial-ItalicMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-BoldItalic' for 'Arial-BlackItalic'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans' for 'ArialMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-Bold' for 'Arial-BoldMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-BoldItalic' for 'Arial-BoldItalicMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-Italic' for 'Arial-ItalicMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSerif' for 'TimesNewRomanPSMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-Bold' for 'Arial-BoldMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-BoldItalic' for 'Arial-BoldItalicMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-Italic' for 'Arial-ItalicMT'
2017-08-22 12:42:11 WARN  PDTrueTypeFont:205 - Using fallback font 'LiberationSans-BoldItalic' for 'Arial-BlackItalic'
.....

**Comment by anjackson** [comment]
We can add a modification to the default logging configuration to only report errors from PDFBox, I guess?

**Comment by thomasegense** [comment]
Thanks. I have upped PDFBox to log on error only in the log4j-override.properties.
