### ISSUE TITLE
Geosearch can't support multiple values and docValues

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#105]
@thomasegense reports seeing this

```
Exception in thread "main" org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/netarchivebuilder: Exception writing document id dd8ooYS3wcrBvm82ZauHNQ==/20170622193210 to the index; possible analysis error: DocValuesField "locations_0_coordinate" appears more than once in this document (only one value is allowed per field)
    at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:577)
    at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
    at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
    at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
    at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:106)
    at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:71)
    at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:85)
    at uk.bl.wa.solr.SolrWebServer.add(SolrWebServer.java:122)
    at uk.bl.wa.indexer.WARCIndexerCommand.checkSubmission(WARCIndexerCommand.java:400)
    at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:330)
    at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:202)
```

This is likely because the old (deprecated) LatLon type the schema is using does not support `multiValued` and `docValues` together. We should use [LatLonPointSpatialField](https://lucene.apache.org/solr/guide/6_6/spatial-search.html) instead.

**Comment by anjackson** [comment]
@thomasegense Can you give that a whirl at some point?

**Comment by anjackson** [comment]
Oops, nope. That's a Solr6 thing.

**Comment by anjackson** [comment]
Hm, okay, so disabling docValues is necessary under Solr 5.5.4.

**Comment by anjackson** [comment]
So, I propose we leave it like this for now, and open a new ticket for upgrading Solr and updating the location field, possibly after having sorted out #106

**Comment by anjackson** [comment]
Now we're on Solr 6, this should be fine.  BUT I'd like to use `SpatialRecursivePrefixTreeFieldType` because this allows heatmaps to be generated (https://lucene.apache.org/solr/guide/6_6/spatial-search.html).

**Comment by anjackson** [comment]
See also https://github.com/ukwa/webarchive-discovery/issues/174
