### ISSUE TITLE
Exception for archives that have a number of documents multiple of the parameter warc.solr.batch_size

### ISSUE THREAD

**Issue by bnfleb** [ukwa/webarchive-discovery#112]
We have sometimes this uncaught exception when indexing with warc-indexer

```
Exception in thread "main" org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8981/solr/discovery: missing content stream
    at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:577)
    at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
    at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
    at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
    at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:106)
    at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:71)
    at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:85)
    at uk.bl.wa.solr.SolrWebServer.add(SolrWebServer.java:122)
    at uk.bl.wa.indexer.WARCIndexerCommand.checkSubmission(WARCIndexerCommand.java:407)
    at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:352)
    at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:202)
```

This happens for archives that have a number of documents multiple of the parameter `warc.solr.batch_size`. It appears that at the end of the indexation, the indexer sends an empty list of documents to Solr.

**Comment by anjackson** [comment]
Okay, I think this was a subtle operator-precedence thing. I've pushed a change that should resolve it. Are you able to test?

**Comment by bnfleb** [comment]
Everything is good now, I no longer have the exception with this correction.
