### ISSUE TITLE
Infinite loop on malformed GZip chunk

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#121]
A particular WARC caused an infinite loop when running under Map Reduce. Running locally, we get:

```
Exception in thread "main" java.lang.RuntimeException: After retry (Offset 314935616)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:512)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:436)
	at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:300)
	at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:202)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at org.archive.util.zip.OpenJDK7InflaterInputStream.fill(OpenJDK7InflaterInputStream.java:244)
	at org.archive.util.zip.OpenJDK7InflaterInputStream.read(OpenJDK7InflaterInputStream.java:162)
	at org.archive.util.zip.OpenJDK7GZIPInputStream.read(OpenJDK7GZIPInputStream.java:122)
	at org.archive.util.zip.GZIPMembersInputStream.read(GZIPMembersInputStream.java:113)
	at org.archive.util.zip.OpenJDK7InflaterInputStream.read(OpenJDK7InflaterInputStream.java:126)
	at org.archive.util.LaxHttpParser.readRawLine(LaxHttpParser.java:84)
	at org.archive.util.LaxHttpParser.readLine(LaxHttpParser.java:112)
	at org.archive.io.warc.WARCRecord.parseHeaders(WARCRecord.java:114)
	at org.archive.io.warc.WARCRecord.<init>(WARCRecord.java:90)
	at org.archive.io.warc.WARCReader.createArchiveRecord(WARCReader.java:95)
	at org.archive.io.warc.WARCReaderFactory$CompressedWARCReader$1.innerNext(WARCReaderFactory.java:290)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.exceptionNext(ArchiveReader.java:537)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:505)
	... 3 more
```

The MR code is built to keep going after an exception, but in this case, because it's the last record that is malformed, it just keeps on going. In short, we should catch `java.io.EOFException` and exit rather than retry.

**Comment by anjackson** [comment]
Okay, we should be good to test now on the main cluster, @GilHoggarth @min2ha. Both the pre-Heritrix-era records and the borked WARC.GZ file should be dealt with.
