### ISSUE TITLE
Faulty URLs causes missing droid-result

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#137]
```
2017-10-12 12:45:32 ERROR WARCPayloadAnalysers:176 - org.apache.commons.httpclient.URIException: Invalid URL encoding: not a valid digit (radix 16): 37: Invalid URL encoding: not a valid digit (radix 16): 37;dd; http://dating-date.dk/arto/)%20no-repeat%2050%%200 @49269483
org.apache.commons.httpclient.URIException: Invalid URL encoding: not a valid digit (radix 16): 37
    at org.apache.commons.httpclient.URI.decode(URI.java:1775)
    at org.apache.commons.httpclient.URI.decode(URI.java:1731)
    at org.apache.commons.httpclient.URI.getName(URI.java:3157)
    at uk.bl.wa.analyser.payload.WARCPayloadAnalysers.analyse(WARCPayloadAnalysers.java:165)
    at uk.bl.wa.indexer.WARCIndexer.extract(WARCIndexer.java:566) 
```
happens because the URL contains `...repeat 50% 0` and has not been error-corrected at that point in the code. This is not a fatal error, but does cause the droid-detection step to be missed. The solution is to use `Normalisation.fixEscapeErrorsAndUnescapeHighOrderUTF8` or similar functionality that handles common URL-errors.

**Comment by tokee** [comment]
Closed by pull #140
