### ISSUE TITLE
Infinite loop when the last record is corrupted

### ISSUE THREAD

**Issue by bnfleb** [ukwa/webarchive-discovery#165]
For some w.arc there are corrupted record. Issue #127 dealed with it. But if it's the last record, we have an infinite loop throwing an error : 
`Feb 21, 2018 5:04:32 PM org.archive.io.ArchiveReader$ArchiveRecordIterator hasNext
WARNING: Trying skip of failed record cleanup of /dta/02/arc/602/BNF-test5-1-256-956977328/BNF-test5-1-256-956977328.arc.gz: {ip-address=209.144.237.79, content-type=im, absolute-offset=11413741, subject-uri=http://www.workholding.com:80/zagblu5.jpg, origin=, length=7932, creation-date=20000429030234, version=null}: invalid distance too far back
java.util.zip.ZipException: invalid distance too far back
	at org.archive.util.zip.OpenJDK7InflaterInputStream.read(OpenJDK7InflaterInputStream.java:168)
	at org.archive.util.zip.OpenJDK7GZIPInputStream.read(OpenJDK7GZIPInputStream.java:122)
	at org.archive.util.zip.GZIPMembersInputStream.read(GZIPMembersInputStream.java:113)
	at org.archive.io.ArchiveRecord.read(ArchiveRecord.java:204)
	at org.archive.io.arc.ARCRecord.read(ARCRecord.java:799)
	at org.archive.io.ArchiveRecord.skip(ArchiveRecord.java:262)
	at org.archive.io.ArchiveRecord.skip(ArchiveRecord.java:248)
	at org.archive.io.ArchiveRecord.close(ArchiveRecord.java:172)
	at org.archive.io.ArchiveReader.cleanupCurrentRecord(ArchiveReader.java:175)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.hasNext(ArchiveReader.java:449)
	at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:340)
	at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:227)`

Error may vary but it's always because of the `hasNext`

**Comment by tokee** [comment]
Closed as pull #166 fixes this.
