### ISSUE TITLE
When specifying XML output, commit should be disabled

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#221]
For debugging or non-direct indexing, the command line option `-o folder` to `warc_indexer` should imput `-d` so that the indexer does not attempt a Solr-commit.

**Comment by anjackson** [comment]
Sorry @tokee I'm not quite understanding that.  The Hadoop variant uses a `dummy-run` flag that prevent POSTing to Solr. Is that the kind of thing you mean?

**Comment by tokee** [comment]
Running `java -jar warc-indexer-3.1.0-SNAPSHOT-jar-with-dependencies.jar -t -o xml some.warc` gives the error
```
2020-05-18 16:00:30 WARN  WARCIndexerCommand:425 - SolrServerException when committing.
org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://localhost:8080/solr/discovery
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:583)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:482)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:463)
	at uk.bl.wa.solr.SolrWebServer.commit(SolrWebServer.java:146)
	at uk.bl.wa.indexer.WARCIndexerCommand.commit(WARCIndexerCommand.java:422)
	at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:317)
	at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:228)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```
As can be seen, the error comes from the `commit` method: Although the `-o` causes the code not to try and send the result to Solr, it still tries to issue a commit when processing has finished.

I am a bit busy putting out a fire, but I'll see if I can fix it and make a pull-request later today or tomorrow.
