### ISSUE TITLE
Tika process exits and skips rest of arc-file parsing.

### ISSUE THREAD

**Issue by thomasegense** [ukwa/webarchive-discovery#45]
This error seems to have been introduced after warc-indexer-1.1.1 since some ARC files that previously parsed are now terminating during Tika analyze.
Branch:branch2.0.x-dev-branch

Various stacktraces from termination:
The first is far most common: : [<DOCTYPE.....

12 14:17:09,313 [Thread-49] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - Started indexing: /netarkiv/0223/filedir/137564-153-20111130050924-00068-kb-prod-har-004.kb.dk.arc with worker #3302
2015-02-12 14:17:16,607 [Thread-13] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - Error processing: /netarkiv/0223/filedir/137564-153-20111129234107-00002-kb-prod-har-004.kb.dk.arc
2015-02-12 14:17:16,607 [Thread-13] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - return code not expected: 1
2015-02-12 14:17:16,607 [Thread-13] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - Error output: Feb 12, 2015 2:17:16 PM org.archive.io.ArchiveReader$ArchiveRecordIterator next
WARNING: Bad Record. Trying skip (Record start 29424030): Size of field name keys does not match count of field values: [<!DOCTYPE, html, PUBLIC, "-//W3C//DTD, XHTML, 1.0, Strict//EN", "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">] (Offset 29424030).
Exception in thread "main" java.lang.RuntimeException: After retry (Offset 29424030)
        at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:512)
        at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:436)
        at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:282)
        at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:197)
Caused by: java.io.IOException: Size of field name keys does not match count of field values: [<html, xmlns="http://www.w3.org/1999/xhtml", xml:lang="da", lang="da">] (Offset 29424140).
        at org.archive.io.arc.ARCRecord.computeMetaData(ARCRecord.java:401)
        at org.archive.io.arc.ARCRecord.parseHeaders(ARCRecord.java:274)
        at org.archive.io.arc.ARCRecord.<init>(ARCRecord.java:206)
        at org.archive.io.arc.ARCReader.createArchiveRecord(ARCReader.java:149)
        at org.archive.io.arc.ARCReader.createArchiveRecord(ARCReader.java:68)
        at org.archive.io.ArchiveReader.get(ArchiveReader.java:151)
        at org.archive.io.ArchiveReader$ArchiveRecordIterator.innerNext(ArchiveReader.java:562)
        at org.archive.io.ArchiveReader$ArchiveRecordIterator.exceptionNext(ArchiveReader.java:537)
        at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:505)

------------------------

2015-02-12 14:16:03,474 [Thread-13] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - Started indexing: /netarkiv/0223/filedir/137564-153-20111129234107-00002-kb-prod-har-004.kb.dk.arc with worker #3287
2015-02-12 14:16:06,181 [Thread-113] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - Error processing: /netarkiv/0223/filedir/137564-153-20111130050924-00068-kb-prod-har-004.kb.dk.arc
2015-02-12 14:16:06,182 [Thread-113] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - return code not expected: 1
2015-02-12 14:16:06,182 [Thread-113] INFO  dk.statsbiblioteket.netarchivesuite.arctika.builder.IndexBuilderConfig - Error output: Feb 12, 2015 2:16:05 PM org.archive.io.ArchiveReader$ArchiveRecordIterator next
WARNING: Bad Record. Trying skip (Record start 31578457): Unparseable header line: [<html><head><title>Object, moved</title></head><body>^M] (Offset 31578457).
Exception in thread "main" java.lang.NumberFormatException: For input string: "href="/sitecore/service/nolayout.aspx?item=%2fsitecore%2fmedia+library%2fimages%2fom_sdu%2ffaellesadministrationen%2fpresse_formidling%2fpdf+filer%2fsdu+nyviden+10+2006+pdf&amp;layout=%7b00000000-0000-0000-0000-000000000000%7d&amp;device=Default">here</a>.</h2>^M"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
        at java.lang.Long.parseLong(Long.java:483)
        at org.archive.io.arc.ARCRecordMetaData.getLength(ARCRecordMetaData.java:129)
        at org.archive.io.ArchiveRecord.available(ArchiveRecord.java:229)
        at org.archive.io.ArchiveRecord.skip(ArchiveRecord.java:246)
        at org.archive.io.ArchiveRecord.close(ArchiveRecord.java:172)
        at org.archive.io.ArchiveReader.cleanupCurrentRecord(ArchiveReader.java:175)
        at org.archive.io.ArchiveReader$ArchiveRecordIterator.hasNext(ArchiveReader.java:449)
        at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:280)
        at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:197)

**Comment by anjackson** [comment]
Is it clear why this used to work, but no longer does?

**Comment by anjackson** [comment]
Sorry for not responding earlier - can you share a failing test file? The latest version (2.2.0-BETA-5) has been run on a very large and messy collection and not fallen over yet!

**Comment by thomasegense** [comment]
Toke has fixed the issue. It was the header parsing that failed when the arc-file was harvested on a windows-server and newline-character was different. I believe you have never experienced it since you only harvest on Linux. It is only only a very small number of arc-files we have that has been harvested on windows.

**Comment by anjackson** [comment]
Okay, thanks for letting me know. I'll close this issue in that case.
