### ISSUE TITLE
Problem in CDX Creation

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/webarchive-discovery#62]
Some MapReduce jobs are failing, having filled up the `stderr` logs with errors like this:

```
    Jun 16, 2015 10:52:56 AM org.archive.io.ArchiveReader$ArchiveRecordIterator hasNext
    WARNING: Trying skip of failed record cleanup of {WARC-Type=response, reader-identifier=BL-20141014234947575-00134-20807~crawler02~8445.warc.gz, WARC-Date=2014-10-14T23:49:34Z, absolute-offset=783769282, Content-Length=969332184, WARC-Record-ID=<urn:uuid:df3ad578-53b3-4155-9060-901222d50559>, WARC-IP-Address=XXX, WARC-Payload-Digest=sha1:QCROFWOEO3APZ4FEB7MPDDDJLLCBGTMK, WARC-Target-URI=http://XXXX, Content-Type=application/http; msgtype=response}: invalid block type
    java.util.zip.ZipException: invalid block type
            at org.archive.util.zip.OpenJDK7InflaterInputStream.read(OpenJDK7InflaterInputStream.java:167)
            at org.archive.util.zip.OpenJDK7GZIPInputStream.read(OpenJDK7GZIPInputStream.java:122)
            at org.archive.io.GZIPMembersInputStream.read(GZIPMembersInputStream.java:115)
            at org.archive.io.ArchiveRecord.read(ArchiveRecord.java:204)
            at org.archive.io.ArchiveRecord.skip(ArchiveRecord.java:262)
            at org.archive.io.ArchiveRecord.skip(ArchiveRecord.java:248)
            at org.archive.io.ArchiveRecord.close(ArchiveRecord.java:172)
            at org.archive.io.ArchiveReader.cleanupCurrentRecord(ArchiveReader.java:172)
            at org.archive.io.ArchiveReader$ArchiveRecordIterator.hasNext(ArchiveReader.java:446)
            at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:498)
            at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:433)
            at org.archive.wayback.resourcestore.indexer.ArchiveReaderCloseableIterator.next(ArchiveReaderCloseableIterator.java:40)
            at org.archive.wayback.resourcestore.indexer.ArchiveReaderCloseableIterator.next(ArchiveReaderCloseableIterator.java:29)
            at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:53)
            at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:52)
            at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:52)
            at uk.bl.wa.hadoop.mapreduce.lib.DereferencingArchiveToCDXRecordReader.nextKeyValue(DereferencingArchiveToCDXRecordReader.java:130)
            at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:456)
            at org.apache.hadoop.mapreduce.MapContext.nextKeyValue(MapContext.java:67)
            at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
            at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:647)
            at org.apache.hadoop.mapred.MapTask.run(MapTask.java:323)
            at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
            at java.security.AccessController.doPrivileged(Native Method)
            at javax.security.auth.Subject.doAs(Subject.java:396)
            at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
            at org.apache.hadoop.mapred.Child.main(Child.java:264)
    Jun 16, 2015 10:52:56 AM org.archive.io.ArchiveReader$ArchiveRecordIterator next
    WARNING: Bad Record. Trying skip (Record start 783769282): invalid block type
```

In theory the code should skip to the next record but it just loops on the same one until the local disk fills.

**Comment by anjackson** [comment]
This is an old ticket, and the indexer has changed a lot (now PyWB based).
