### ISSUE TITLE
Date-based partial updates not working

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#64]
Previously, we had no problem sending the CRAWL_DATES field in as a 'atomic update' or 'partial update'. See [mergeField](https://github.com/ukwa/webarchive-discovery/blob/b66ed3052f9cc15e8972ea5158d9382e31e92014/warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecord.java#L176)

However, now, if there is already a document at a given ID (i.e. HASH+URL), an update document (like that attached below) will fail with this error:

```
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Invalid Date String:'Thu Jan 03 20:35:40 GMT 2013'
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:495)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:199)
	at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:118)
	at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:116)
	at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:102)
	at uk.bl.wa.solr.SolrWebServer.updateSolrDoc(SolrWebServer.java:132)
	at uk.bl.wa.indexer.WARCIndexerCommand.checkSubmission(WARCIndexerCommand.java:387)
	at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:327)
	at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:200)
```
Even though the date is not formatted like that in the added document. It seems to be a problem with Solr.

Here's the example.

```xml
<?xml version="1.0"?>
<doc boost="1.0">
  <field name="id">sha1:LGAPHIGJP6QA7LTKHQSTVMGCFULCVWRO/ttXuNZD38xTJJLFqHmJNqw==</field>
  <field name="source_file">flashfrozen-jwat-recompressed.warc.gz</field>
  <field name="source_file_offset">849</field>
  <field name="url">http://bits.wikimedia.org/en.wikipedia.org/load.php?debug=false&amp;lang=en&amp;modules=site&amp;only=scripts&amp;skin=vector&amp;*</field>
  <field name="url_type">normal</field>
  <field name="record_type">response</field>
  <field name="resourcename">load.php</field>
  <field name="content_type_ext">php</field>
  <field name="host">bits.wikimedia.org</field>
  <field name="domain">wikimedia.org</field>
  <field name="public_suffix">org</field>
  <field name="server">Apache</field>
  <field name="server">PHP/5.3.10-1ubuntu3.4+wmf1</field>
  <field name="content_type_served">text/javascript; charset=utf-8</field>
  <field name="content_length">8963</field>
  <field name="hash">sha1:LGAPHIGJP6QA7LTKHQSTVMGCFULCVWRO</field>
  <field name="crawl_dates" update="add">2013-01-03T20:35:40Z</field>
  <field name="crawl_years" update="add">2013</field>
  <field name="crawl_date">2013-01-03T20:35:40Z</field>
  <field name="crawl_year">2013</field>
  <field name="wayback_date">20130103203540</field>
  <field name="content">0022f4 ...</field>
  <field name="content_text_length">8962</field>
  <field name="content_type">text/plain</field>
  <field name="content_encoding">windows-1252</field>
  <field name="content_ffb">30303232</field>
  <field name="content_type_droid">application/octet-stream</field>
  <field name="content_type_tika">text/plain; charset=windows-1252</field>
  <field name="content_type_full">text/plain; charset=windows-1252</field>
  <field name="content_type_norm">text</field>
  <field name="content_language">en</field>
</doc>
```

If you submit this twice, the second time will fail.

**Comment by anjackson** [comment]
Originally raised by @lintool

**Comment by anjackson** [comment]
Okay, so this looks like a Solr bug. Disabling docValues for crawl_dates is an acceptable workaround, as we are moving away from multiple crawl_dates on single hash-based records and towards giving every revisit it's own record.

**Comment by anjackson** [comment]
Confirmed by @tokee here: https://twitter.com/tokeeskildsen/status/620652293097177088

I'm happy to go with disabling docValues for this field for now. We can consider reinstating this later.

**Comment by anjackson** [comment]
n.b. We're deprecating this approach for now anyway as collapsing records down by hash is harder to scale.
