### ISSUE TITLE
unknown field 'source_file_s'

### ISSUE THREAD

**Issue by nasry** [ukwa/webarchive-discovery#75]
I followed the quickstart to test webarchieve-discovery but when I run this commande : 

> java -jar warc-indexer-2.0.1-20150116.110435-2-jar-with-dependencies.jar  -s http://localhost:8080/discovery -t warc-indexer/src/test/resources/wikipedia-mona-lisa/flashfrozen-jwat-recompressed.warc.gz

I got HttpSolrServer$RemoteSolrException, here is the output of the command : 

`2016-10-26 14:23:49 INFO  WARCIndexer:153 - Extract text = true
2016-10-26 14:23:49 INFO  WARCIndexer:156 - Store text = true
2016-10-26 14:23:49 INFO  WARCIndexer:158 - hashUrlId = true
2016-10-26 14:23:49 INFO  WARCIndexer:198 - Hashing & Caching thresholds are: < 10485760 in memory, < 104857600 on disk.
2016-10-26 14:23:49 INFO  WARCIndexer:201 - Setting up analysers...
2016-10-26 14:23:49 INFO  WARCPayloadAnalysers:85 - Image feature extraction = true
2016-10-26 14:23:52 INFO  TikaExtractor:116 - Config: MIME exclude list: [x-tar, x-gzip, bz, lz, compress, zip, javascript, css, octet-stream]
2016-10-26 14:23:52 INFO  TikaExtractor:119 - Config: Parser timeout (ms) 300000
2016-10-26 14:23:52 INFO  TikaExtractor:122 - Config: Maximum length of text to extract (characters) 524288
2016-10-26 14:23:52 INFO  TikaExtractor:126 - Config: extractAllMetadata false
2016-10-26 14:23:52 INFO  TikaExtractor:129 - Config: useBoilerpipe false
2016-10-26 14:23:52 INFO  HTMLAnalyser:59 - HTML - Extract resource links false
2016-10-26 14:23:52 INFO  HTMLAnalyser:61 - HTML - Extract host links true
2016-10-26 14:23:52 INFO  HTMLAnalyser:63 - HTML - Extract domain links true
2016-10-26 14:23:52 INFO  HTMLAnalyser:65 - HTML - Extract elements used true
2016-10-26 14:23:52 INFO  ImageAnalyser:69 - Image - detect faces = true
2016-10-26 14:23:52 INFO  ImageAnalyser:71 - Image - max size in bytes 1048576
2016-10-26 14:23:52 INFO  ImageAnalyser:74 - Image sample rate 0.1
2016-10-26 14:23:52 INFO  FaceDetectionParser:90 - Face detection enabled.
2016-10-26 14:23:52 INFO  FaceDetectionParser:92 - Dominant colour extraction enabled.
2016-10-26 14:23:52 INFO  LanguageAnalyser:51 - Constructing...
2016-10-26 14:23:52 INFO  WARCIndexer:206 - Initialisation of WARCIndexer complete.
Parsing Archive File [1/1]:warc-indexer/src/test/resources/wikipedia-mona-lisa/flashfrozen-jwat-recompressed.warc.gz
Exception in thread "main" org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: ERROR: [doc=sha1:LGAPHIGJP6QA7LTKHQSTVMGCFULCVWRO/ttXuNZD38xTJJLFqHmJNqw==] unknown field 'source_file_s'
    at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:495)
    at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:199)
    at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:118)
    at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:68)
    at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:54)
    at uk.bl.wa.solr.SolrWebServer.add(SolrWebServer.java:116)
    at uk.bl.wa.indexer.WARCIndexerCommand.checkSubmission(WARCIndexerCommand.java:344)
    at uk.bl.wa.indexer.WARCIndexerCommand.parseWarcFiles(WARCIndexerCommand.java:296)
    at uk.bl.wa.indexer.WARCIndexerCommand.main(WARCIndexerCommand.java:190)
`

**Comment by anjackson** [comment]
Hello, sorry for not replying. Looks like the schema is skewed - We were working on a separate branch and I need to check we're up to date. I'll take a look ASAP.

**Comment by anjackson** [comment]
Okay, we have been working on the `2.2.x-dev-branch` - I just merged it into `master` so it should now be consistent and be using the `source_file` field to store that information.

**Comment by nasry** [comment]
@anjackson  thanks for the reply now it works fine

**Comment by anjackson** [comment]
Excellent. Thanks for letting us know.

**Comment by sh0416** [comment]
Actually, I think I have same problem. I just follow the tutorial you provided. Is there any problem or issue with that?

**Comment by sh0416** [comment]
Hmm.. is this project work only in Java 7???

**Comment by anjackson** [comment]
@sh0416 We're stuck on Java 6 - I attempted to move to Java 7 and then had to roll back. Which branch are you using? `master`?

**Comment by anjackson** [comment]
Ah-ha! I see I'd put a link to an old version as a binary download. Sorry about that. I've [updated the Quick Start](https://github.com/ukwa/webarchive-discovery/wiki/Quick-Start) to rely on a local build instead.

**Comment by sh0416** [comment]
Yes. I just clone it so it will be master. I install java today so that the version of jdk is 1.8. I try to install lower version of java, but oracle doesn't provided anymore, I think.

**Comment by anjackson** [comment]
I'm going to try re-building it myself under JDK 1.8, which I'm pretty sure works fine and still builds 1.6-compatible code.

**Comment by anjackson** [comment]
Okay, just did a clean build and re-tests and it's working for me. I think the issue might be that some part of the system, like the test server, is 'remembering' the old schema. Try performing a full clean before starting the test server.

**Comment by sh0416** [comment]
Okay, I will try that. Thanks!!! :)

**Comment by sh0416** [comment]
It works well. I appreciate your help. Actually, this project is exactly what I want. :)

**Comment by anjackson** [comment]
Excellent! I hope it works well for you. Please do let us know if you make/publish something that involved using this software. We're always interested in use cases.
