### ISSUE TITLE
Off-spec URIs causing errors and hence dropped records

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#89]
```
java.net.URISyntaxException: Illegal character in query at index 152: http://www.dailymail.co.uk/sport/football/article-2513140/Manchester-United-legend-survivor-Munich-air-disaster-Bill-Foulkes-dies-aged-81.html?ico=sport^headlines
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3092)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at java.net.URL.toURI(URL.java:942)
	at uk.bl.wa.indexer.WARCIndexer.extract(WARCIndexer.java:560)
	at uk.bl.wa.indexer.WARCIndexer.extract(WARCIndexer.java:257)
	at uk.bl.wa.hadoop.indexer.WARCIndexerMapper.innerMap(WARCIndexerMapper.java:133)
	at uk.bl.wa.hadoop.indexer.WARCIndexerMapper.map(WARCIndexerMapper.java:190)
	at uk.bl.wa.hadoop.indexer.WARCIndexerMapper.map(WARCIndexerMapper.java:33)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:391)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:325)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
	at org.apache.hadoop.mapred.Child.main(Child.java:264)
```

**Comment by anjackson** [comment]
URIs now being escaped properly.
