### ISSUE TITLE
Cope when language detection hits an infinite probability

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#92]
During large runs, we're seeing quite a lot of these:

```
2017-07-01 22:34:56 ERROR WARCIndexerMapper:154 - java.lang.IllegalArgumentException: Probability must be <= 1 but was Infinity; http://www.thetimes.co.uk/tto/news/world/middleeast/article3949962.ece; 5721693
java.lang.IllegalArgumentException: Probability must be <= 1 but was Infinity
	at com.optimaize.langdetect.DetectedLanguage.<init>(DetectedLanguage.java:46)
	at com.optimaize.langdetect.LanguageDetectorImpl.sortProbability(LanguageDetectorImpl.java:253)
	at com.optimaize.langdetect.LanguageDetectorImpl.getProbabilities(LanguageDetectorImpl.java:134)
	at org.apache.tika.langdetect.OptimaizeLangDetector.detectAll(OptimaizeLangDetector.java:166)
	at org.apache.tika.language.detect.LanguageDetector.detect(LanguageDetector.java:216)
	at org.apache.tika.language.detect.LanguageDetector.detect(LanguageDetector.java:236)
	at uk.bl.wa.analyser.text.LanguageAnalyser.analyse(LanguageAnalyser.java:77)
	at uk.bl.wa.analyser.text.TextAnalysers.analyse(TextAnalysers.java:101)
	at uk.bl.wa.indexer.WARCIndexer.extract(WARCIndexer.java:590)
	at uk.bl.wa.indexer.WARCIndexer.extract(WARCIndexer.java:257)
	at uk.bl.wa.hadoop.indexer.WARCIndexerMapper.innerMap(WARCIndexerMapper.java:133)
	at uk.bl.wa.hadoop.indexer.WARCIndexerMapper.map(WARCIndexerMapper.java:190)
	at uk.bl.wa.hadoop.indexer.WARCIndexerMapper.map(WARCIndexerMapper.java:33)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:391)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:325)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
	at org.apache.hadoop.mapred.Child.main(Child.java:264)
```

Our analyser should probably neutralise this for now, but we should consider reporting it back to Tika or Optimaize.

**Comment by anjackson** [comment]
Looks good. The error is recorded but does not prevent record creation.
