### ISSUE TITLE
Missing WARC processing method

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/webarchive-discovery#93]
From ingest dev test Monday July 3 http://194.66.232.87:50030/jobdetails.jsp?jobid=job_201706291604_0020&refresh=30

> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/mapred/local/dir/taskTracker/hdfs/jobcache/job_201706291604_0020/jars/lib/slf4j-log4j12-1.5.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/usr/lib/hadoop-0.20/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> Exception in thread "1499075248289" java.lang.NoSuchMethodError: org.apache.cxf.common.util.StringUtils.split(Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
> 	at org.apache.cxf.jaxrs.utils.JAXRSUtils.getPathSegments(JAXRSUtils.java:186)
> 	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.setPathAndMatrix(UriBuilderImpl.java:650)
> 	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.setUriParts(UriBuilderImpl.java:631)
> 	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.uri(UriBuilderImpl.java:607)
> 	at org.apache.cxf.jaxrs.client.LocalClientState.resetCurrentUri(LocalClientState.java:70)
> 	at org.apache.cxf.jaxrs.client.LocalClientState.<init>(LocalClientState.java:51)
> 	at org.apache.cxf.jaxrs.client.WebClient.<init>(WebClient.java:98)
> 	at org.apache.cxf.jaxrs.client.WebClient.<init>(WebClient.java:94)
> 	at org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean.createWebClient(JAXRSClientFactoryBean.java:223)
> 	at org.apache.cxf.jaxrs.client.WebClient.create(WebClient.java:116)
> 	at org.apache.tika.parser.journal.GrobidRESTParser.parse(GrobidRESTParser.java:81)
> 	at org.apache.tika.parser.journal.JournalParser.parse(JournalParser.java:60)
> 	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
> 	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
> 	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:135)
> 	at uk.bl.wa.solr.TikaExtractor$ParseRunner.run(TikaExtractor.java:424)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by anjackson** [comment]
So, there appear to be classpath conflict, as Nanite/DROID is bringing in an old version of CXF we don't need.

However, I'm not sure I understand why Tika is attempting to contact a GROBID service.

**Comment by anjackson** [comment]
Okay, just appears to be default behaviour, i.e. use GROBID if it's there. Doesn't seem to slow things down so all good.

**Comment by anjackson** [comment]
Hm, moved the problem further along...

```
Exception in thread "1499201625999" java.lang.NoSuchMethodError: org.springframework.util.ClassUtils.isCglibProxyClass(Ljava/lang/Class;)Z
	at org.apache.cxf.common.util.SpringAopClassHelper.getRealClassInternal(SpringAopClassHelper.java:86)
	at org.apache.cxf.common.util.ClassHelper.getRealClass(ClassHelper.java:85)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.setCommonProviders(ProviderFactory.java:475)
	at org.apache.cxf.jaxrs.client.ClientProviderFactory.setProviders(ClientProviderFactory.java:74)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.initFactory(ProviderFactory.java:129)
	at org.apache.cxf.jaxrs.client.ClientProviderFactory.createInstance(ClientProviderFactory.java:55)
	at org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean.initClient(JAXRSClientFactoryBean.java:377)
	at org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean.createWebClient(JAXRSClientFactoryBean.java:225)
	at org.apache.cxf.jaxrs.client.WebClient.create(WebClient.java:116)
	at org.apache.tika.parser.journal.GrobidRESTParser.parse(GrobidRESTParser.java:81)
	at org.apache.tika.parser.journal.JournalParser.parse(JournalParser.java:60)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:135)
	at uk.bl.wa.solr.TikaExtractor$ParseRunner.run(TikaExtractor.java:426)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by anjackson** [comment]
Given this is not actually preventing the thing from working, I'm going to close this down until it causes an actual problem.

**Comment by anjackson** [comment]
Okay, one last go at tidying up...

**Comment by anjackson** [comment]
Still seeing this:
```
java.lang.NoSuchMethodError: org.springframework.util.ClassUtils.isCglibProxyClass(Ljava/lang/Class;)Z
	at org.apache.cxf.common.util.SpringAopClassHelper.getRealClassInternal(SpringAopClassHelper.java:86)
	at org.apache.cxf.common.util.ClassHelper.getRealClass(ClassHelper.java:85)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.setCommonProviders(ProviderFactory.java:475)
	at org.apache.cxf.jaxrs.client.ClientProviderFactory.setProviders(ClientProviderFactory.java:74)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.initFactory(ProviderFactory.java:129)
	at org.apache.cxf.jaxrs.client.ClientProviderFactory.createInstance(ClientProviderFactory.java:55)
	at org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean.initClient(JAXRSClientFactoryBean.java:377)
	at org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean.createWebClient(JAXRSClientFactoryBean.java:225)
	at org.apache.cxf.jaxrs.client.WebClient.create(WebClient.java:116)
	at org.apache.tika.parser.journal.GrobidRESTParser.parse(GrobidRESTParser.java:81)
	at org.apache.tika.parser.journal.JournalParser.parse(JournalParser.java:60)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:135)
	at uk.bl.wa.solr.TikaExtractor$ParseRunner.run(TikaExtractor.java:429)
	at java.lang.Thread.run(Thread.java:745)
```

Giving up for now as this is not actually causing major problems.
